import { createFileRoute, Link } from '@tanstack/react-router'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'
import { Search, Play } from 'lucide-react'
import { useState } from 'react'
import { getVideos } from '@/lib/orbit.functions'
import { Shell, Empty } from '@/components/orbit-shell'
import { Button } from '@/components/ui/button'
const opts=queryOptions({queryKey:['videos'],queryFn:()=>getVideos(),staleTime:300000})
export const Route=createFileRoute('/videos/')({head:()=>({meta:[{title:'Buscar anime — Anime Orbit'},{name:'description',content:'Busca anime y explora sus capítulos disponibles en Anime Orbit.'},{property:'og:title',content:'Buscar anime — Anime Orbit'},{property:'og:description',content:'Busca capítulos de anime disponibles.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),loader:({context})=>context.queryClient.ensureQueryData(opts),component:Videos,errorComponent:()=> <Shell title="Buscar"><Empty title="No se pudieron cargar los videos" detail="Inténtalo de nuevo más tarde."/></Shell>})
function Videos(){const {data}=useSuspenseQuery(opts);const [filter,setFilter]=useState('Todos');const [search,setSearch]=useState('');const filtered=data.filter(v=>(filter==='Todos'||(filter==='En emisión'?v.status==='airing':v.status==='finished'))&&v.title.toLowerCase().includes(search.toLowerCase()));return <Shell title="Buscar"><label className="mb-6 flex h-13 items-center gap-3 rounded-xl bg-card px-4 text-muted-foreground"><Search size={21} className="shrink-0"/><input aria-label="Buscar anime" className="h-full min-w-0 flex-1 bg-transparent text-foreground outline-none placeholder:text-muted-foreground" placeholder="Buscar" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="hide-scrollbar mb-7 flex gap-2 overflow-x-auto">{['Todos','En emisión','Finalizados'].map(f=><Button key={f} size="sm" onClick={()=>setFilter(f)} variant={filter===f?'default':'secondary'} className="shrink-0 rounded-full px-4">{f}</Button>)}</div>{filtered.length?<div className="grid grid-cols-2 gap-x-3 gap-y-7 sm:grid-cols-3 md:grid-cols-4">{filtered.map(v=><Link key={v.id} to="/videos/$id" params={{id:v.id}} className="group min-w-0"><div className="relative aspect-[2/3] overflow-hidden rounded-lg border border-border bg-card">{v.cover_url&&<img onError={e => { e.currentTarget.style.visibility = "hidden" }} referrerPolicy="no-referrer" src={v.cover_url} alt="" loading="lazy" className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"/>}<span className="absolute bottom-2 right-2 flex size-8 items-center justify-center rounded-full bg-nav/85 text-foreground"><Play size={14} fill="currentColor"/></span></div><div className="mt-2 flex items-center gap-1.5"><span className="size-1.5 rounded-full bg-primary"/><span className="text-[10px] text-muted-foreground">{v.status==='airing'?'En emisión':'Finalizado'}</span></div><h2 className="mt-1 line-clamp-2 text-xs font-semibold leading-4 sm:text-sm">{v.title}</h2><p className="mt-1 text-[11px] text-muted-foreground">{v.video_episodes?.length??0} episodios · Último: {Math.max(0,...(v.video_episodes??[]).map((e: { number: number })=>Number(e.number)))||'—'}</p></Link>)}</div>:<Empty title={search?'Sin resultados':'Sin videos disponibles'} detail={search?'Prueba con otro título.':'Los videos aparecerán aquí cuando se añadan.'} icon={Search}/>}</Shell>}
