import { createFileRoute,Link } from '@tanstack/react-router'
import { queryOptions,useSuspenseQuery } from '@tanstack/react-query'
import { Search,Play } from 'lucide-react'
import { useState } from 'react'
import { getVideos } from '@/lib/orbit.functions'
import { Shell,Empty } from '@/components/orbit-shell'
import { Button } from '@/components/ui/button'
const opts=queryOptions({queryKey:['videos'],queryFn:()=>getVideos(),staleTime:300000})
export const Route=createFileRoute('/videos/')({head:()=>({meta:[{title:'Videos — Anime Orbit'},{name:'description',content:'Explora capítulos y servidores de reproducción de anime.'},{property:'og:title',content:'Videos — Anime Orbit'},{property:'og:description',content:'Descubre capítulos de anime disponibles.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),loader:({context})=>context.queryClient.ensureQueryData(opts),component:Videos,errorComponent:()=> <Shell title="Videos"><Empty title="No se pudieron cargar los videos" detail="Inténtalo de nuevo más tarde."/></Shell>})
function Videos(){const {data}=useSuspenseQuery(opts);const [filter,setFilter]=useState('Todos');const [search,setSearch]=useState('');const filtered=data.filter(v=>(filter==='Todos'||(filter==='En emisión'?v.status==='airing':v.status==='finished'))&&v.title.toLowerCase().includes(search.toLowerCase()));return <Shell title="Videos" subtitle="Elige una historia y entra en órbita." back="/configuracion"><label className="mb-5 flex items-center gap-3 rounded-xl border border-border bg-card/70 px-4 text-muted-foreground"><Search size={18}/><input className="h-12 min-w-0 flex-1 bg-transparent text-foreground outline-none placeholder:text-muted-foreground" placeholder="Buscar anime" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="hide-scrollbar mb-7 flex gap-2 overflow-x-auto">{['Todos','En emisión','Finalizados'].map(f=><Button key={f} size="sm" onClick={()=>setFilter(f)} variant={filter===f?'default':'secondary'} className="shrink-0 rounded-full px-4">{f}</Button>)}</div>{filtered.length?<div className="grid grid-cols-2 gap-x-4 gap-y-8 sm:grid-cols-3 md:grid-cols-4">{filtered.map(v=><Link key={v.id} to="/videos/$id" params={{id:v.id}} className="group min-w-0"><div className="relative aspect-[2/3] overflow-hidden rounded-md bg-secondary">{v.cover_url&&<img src={v.cover_url} alt={v.title} loading="lazy" className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"/>}<span className="glass absolute bottom-2 right-2 flex size-9 items-center justify-center rounded-full text-primary"><Play size={16} fill="currentColor"/></span></div><div className="mt-3 flex items-center gap-2"><span className="size-1.5 rounded-full bg-primary"/><span className="text-[10px] uppercase tracking-wider text-muted-foreground">{v.status==='airing'?'En emisión':'Finalizado'}</span></div><h2 className="mt-1 line-clamp-2 text-sm font-semibold leading-5">{v.title}</h2><p className="mt-1 text-xs text-muted-foreground">{v.video_episodes?.length??0} capítulos · Último: {Math.max(0,...(v.video_episodes??[]).map((e: { number: number })=>Number(e.number)))||'—'}</p></Link>)}</div>:<Empty title="Sin videos disponibles" detail={search?'No hay resultados para esta búsqueda.':'Añade una fuente compatible desde Administración para incorporar capítulos reales.'}/>}</Shell>}
