import { Bookmark, BookmarkCheck, CalendarDays, Clock3, Radio } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { useEffect, useState } from 'react'
import { useServerFn } from '@tanstack/react-start'
import { toggleSaved } from '@/lib/orbit.functions'
import { supabase } from '@/integrations/supabase/client'
import { toast } from 'sonner'
import { readLocalCollection, setLocalCollection } from '@/lib/local-collection'
export type Anime = { id:string; title_romaji:string; title_english:string|null; title_native:string|null; cover_url:string|null; synopsis:string|null; genres:string[]; studio:string|null; platforms:string[]; season:string|null; release_at:string|null; airing_at:string|null; date_confirmed:boolean; status:string|null; source_name:string; last_checked_at:string }
export function AnimeRow({anime, initialSaved=false, timezone='UTC'}:{anime:Anime;initialSaved?:boolean;timezone?:string}) {
  const [saved,setSaved]=useState(initialSaved)
  const toggle=useServerFn(toggleSaved)
  useEffect(() => {
    let mounted = true
    supabase.auth.getUser().then(({data}) => { if (mounted) setSaved(data.user ? initialSaved : readLocalCollection().includes(anime.id)) })
    return () => { mounted = false }
  }, [anime.id, initialSaved])
  const date=anime.airing_at ?? anime.release_at
  let formatted='Por confirmar', time='Por confirmar'
  if(date) { try { formatted=new Intl.DateTimeFormat('es',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:timezone}).format(new Date(date)); if(anime.airing_at) time=new Intl.DateTimeFormat('es',{hour:'2-digit',minute:'2-digit',timeZone:timezone}).format(new Date(date)) } catch { /* invalid timezone */ } }
  const onSave=async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user){const ids=readLocalCollection(); const wasSaved=ids.includes(anime.id);setLocalCollection(wasSaved?ids.filter(id=>id!==anime.id):[anime.id,...ids]);setSaved(!wasSaved);toast.success(wasSaved?'Quitado de guardados':'Guardado en este dispositivo');return} try {await toggle({data:{id:anime.id,saved}});setSaved(!saved);toast.success(saved?'Quitado de guardados':'Guardado')}catch {toast.error('No se pudo guardar')} }
  return <article className="group border-t border-border py-6 sm:py-7"><div className="flex gap-4 sm:gap-6"><div className="w-[98px] shrink-0 sm:w-[138px]"><div className="aspect-[2/3] overflow-hidden rounded-md bg-secondary">{anime.cover_url && <img referrerPolicy="no-referrer" src={anime.cover_url} alt={`Portada de ${anime.title_romaji}`} loading="lazy" className="h-full w-full object-cover"/>}</div></div><div className="min-w-0 flex-1"><div className="mb-2 flex items-start justify-between gap-2"><div className="min-w-0"><p className="mb-1 text-[10px] font-semibold uppercase tracking-[0.16em] text-primary">{anime.season ?? 'TEMPORADA POR CONFIRMAR'}</p><h2 className="text-lg leading-6 font-semibold sm:text-2xl">{anime.title_english || anime.title_romaji}</h2><p className="mt-1 text-xs text-muted-foreground">{anime.title_native || anime.title_romaji}</p></div><Button variant="ghost" size="icon" onClick={onSave} aria-label={saved?'Quitar de guardados':'Guardar anime'} className="shrink-0 text-primary">{saved?<BookmarkCheck size={19}/>:<Bookmark size={19}/>}</Button></div><div className="mt-3 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1.5 text-foreground"><CalendarDays size={13} className="text-primary"/>{formatted}</span><span className="inline-flex items-center gap-1"><Clock3 size={13}/>{time} · {timezone}</span></div><div className="mt-2.5 flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-0.5 text-[10px] font-medium ${anime.date_confirmed?'bg-primary/15 text-primary':'bg-secondary text-muted-foreground'}`}>{anime.date_confirmed?'Confirmada':'Por confirmar'}</span><span className="inline-flex items-center gap-1 text-[11px] text-muted-foreground"><Radio size={12}/>{anime.status==='RELEASING'?'En emisión':anime.status==='NOT_YET_RELEASED'?'Próximamente':anime.status || 'Por confirmar'}</span></div><p className="mt-3 line-clamp-2 text-xs leading-5 text-muted-foreground sm:text-sm">{anime.synopsis || 'Sinopsis por confirmar'}</p><div className="mt-3 flex flex-wrap gap-x-3 gap-y-1 text-[11px] text-muted-foreground"><span>{anime.genres?.slice(0,3).join(' · ') || 'Géneros por confirmar'}</span><span>{anime.studio || 'Estudio por confirmar'}</span><span>{anime.platforms?.join(', ') || 'Plataforma por confirmar'}</span></div><p className="mt-3 text-[10px] text-muted-foreground/70">Fuente: {anime.source_name} · Actualizado: {new Date(anime.last_checked_at).toLocaleDateString('es')}</p></div></div></article>
}
